// Logo C, "Flare at the horizon", from the user-supplied Logo directions mockup.
// Run from the repository root: swift tool/generate_brand_assets.swift
// CoreGraphics renders the PNGs; the same geometry produces SVG and Android XML.
import AppKit

let repo = URL(fileURLWithPath: CommandLine.arguments[0])
    .deletingLastPathComponent().deletingLastPathComponent().standardizedFileURL
let rays: [[CGFloat]] = [
    [72, 64, 92, 64], [65, 47, 79, 33], [48, 40, 48, 20],
    [31, 47, 17, 33], [24, 64, 4, 64], [10, 82, 86, 82],
]
let circle = CGRect(x: 37, y: 53, width: 22, height: 22)
let ink = "#1B1B19", pale = "#F2F1EC", rust = "#B93A0B", orange = "#F26A2E"
let adaptiveScale: CGFloat = 56 / 96
let adaptiveOffset: CGFloat = 26
// Include stroke caps and the flare's radius in circular mask bounds.
let rayReach = rays.flatMap {
    [hypot($0[0] - 48, $0[1] - 48), hypot($0[2] - 48, $0[3] - 48)]
}.max()! + 4
let reach = max(rayReach, hypot(circle.midX - 48, circle.midY - 48) + 11)
precondition(reach * adaptiveScale < 33, "Adaptive artwork exceeds its safe circle")
precondition(reach * (160 / 96) < 96, "Splash artwork exceeds its visible circle")

func number(_ value: CGFloat) -> String { String(format: "%g", Double(value)) }
let rayPath = rays.map { "M\(number($0[0])),\(number($0[1]))L\(number($0[2])),\(number($0[3]))" }.joined()
let circlePath = "M37,64a11,11 0 1,0 22,0a11,11 0 1,0 -22,0z"

func save(_ data: Data, _ relative: String) throws {
    let url = repo.appendingPathComponent(relative)
    try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
    try data.write(to: url)
}

func saveText(_ text: String, _ relative: String) throws {
    try save(Data(text.utf8), relative)
}

func color(_ hex: String) -> CGColor {
    let value = UInt32(hex.dropFirst(), radix: 16)!
    return CGColor(srgbRed: CGFloat((value >> 16) & 255) / 255,
                   green: CGFloat((value >> 8) & 255) / 255,
                   blue: CGFloat(value & 255) / 255, alpha: 1)
}

func mark(_ context: CGContext, stroke: String, flare: String) {
    context.setStrokeColor(color(stroke))
    context.setLineWidth(8)
    context.setLineCap(.round)
    for ray in rays {
        context.move(to: CGPoint(x: ray[0], y: ray[1]))
        context.addLine(to: CGPoint(x: ray[2], y: ray[3]))
    }
    context.strokePath()
    context.setFillColor(color(flare))
    context.fillEllipse(in: circle)
}

func raster(size: Int, logicalSize: CGFloat, draw: (CGContext) -> Void) -> CGImage {
    let pixels = size * 4 // Supersample so the smallest launcher and widget previews have clean edges.
    let context = CGContext(data: nil, width: pixels, height: pixels, bitsPerComponent: 8,
                            bytesPerRow: pixels * 4, space: CGColorSpace(name: CGColorSpace.sRGB)!,
                            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)!
    context.translateBy(x: 0, y: CGFloat(pixels))
    context.scaleBy(x: CGFloat(pixels) / logicalSize, y: -CGFloat(pixels) / logicalSize)
    draw(context)
    let output = CGContext(data: nil, width: size, height: size, bitsPerComponent: 8,
                           bytesPerRow: size * 4, space: CGColorSpace(name: CGColorSpace.sRGB)!,
                           bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)!
    output.interpolationQuality = .high
    output.draw(context.makeImage()!, in: CGRect(x: 0, y: 0, width: size, height: size))
    return output.makeImage()!
}

func png(_ image: CGImage, _ relative: String) throws {
    try save(NSBitmapImageRep(cgImage: image).representation(using: .png, properties: [:])!, relative)
}

func launcher(_ context: CGContext) {
    context.setFillColor(color(ink))
    context.addPath(CGPath(roundedRect: CGRect(x: 0, y: 0, width: 96, height: 96),
                          cornerWidth: 22, cornerHeight: 22, transform: nil))
    context.fillPath()
    context.translateBy(x: 17, y: 17)
    context.scaleBy(x: 62 / 96, y: 62 / 96)
    mark(context, stroke: pale, flare: orange)
}

func svg(stroke: String, flare: String) -> String {
    """
    <!-- Generated by tool/generate_brand_assets.swift. -->
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96">
      <title>Hudyat: flare at the horizon</title>
      <path d="\(rayPath)" fill="none" stroke="\(stroke)" stroke-width="8" stroke-linecap="round"/>
      <circle cx="48" cy="64" r="11" fill="\(flare)"/>
    </svg>

    """
}

func vector(size: Int, viewport: Int = 96, stroke: String, flare: String,
            scale: CGFloat = 1, offset: CGFloat = 0) -> String {
    """
    <?xml version="1.0" encoding="utf-8"?>
    <!-- Generated logo C. Regenerate with swift tool/generate_brand_assets.swift. -->
    <vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="\(size)dp" android:height="\(size)dp"
        android:viewportWidth="\(viewport)" android:viewportHeight="\(viewport)">
        <group android:scaleX="\(number(scale))" android:scaleY="\(number(scale))"
            android:translateX="\(number(offset))" android:translateY="\(number(offset))">
            <path android:fillColor="@android:color/transparent"
                android:strokeColor="\(stroke)" android:strokeWidth="8"
                android:strokeLineCap="round" android:pathData="\(rayPath)"/>
            <path android:fillColor="\(flare)" android:pathData="\(circlePath)"/>
        </group>
    </vector>

    """
}

try saveText(svg(stroke: ink, flare: rust), "assets/brand/source/hudyat-mark-c-light.svg")
try saveText(svg(stroke: pale, flare: orange), "assets/brand/source/hudyat-mark-c-dark.svg")
try png(raster(size: 1024, logicalSize: 96, draw: launcher), "assets/brand/source/hudyat-launcher-c.png")
for (scale, folder) in [(1, ""), (2, "2.0x/"), (3, "3.0x/")] {
    try png(raster(size: 32 * scale, logicalSize: 96) { mark($0, stroke: ink, flare: rust) },
            "assets/brand/\(folder)hudyat_mark_c.png")
}
for (density, size) in [("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)] {
    try png(raster(size: size, logicalSize: 96, draw: launcher),
            "android/app/src/main/res/mipmap-\(density)/ic_launcher.png")
}
let res = "android/app/src/main/res/"
// 56dp artwork in the 108dp foreground stays inside the 66dp safe circle,
// including rounded stroke caps at the ends of the horizon.
try saveText(vector(size: 108, viewport: 108, stroke: pale, flare: orange,
                    scale: adaptiveScale, offset: adaptiveOffset), res + "drawable/ic_launcher_foreground.xml")
try saveText(vector(size: 108, viewport: 108, stroke: "#FFFFFF", flare: "#FFFFFF",
                    scale: adaptiveScale, offset: adaptiveOffset), res + "drawable/ic_launcher_monochrome.xml")
try saveText(vector(size: 22, stroke: "@color/widget_text", flare: "@color/widget_accent"),
             res + "drawable/ic_widget_logo.xml")
try saveText(vector(size: 160, stroke: pale, flare: orange), res + "drawable/ic_brand_c_dark.xml")
// Android 12 reserves a 288dp icon canvas with a 192dp visible circle.
// Inset the 160dp artwork so its horizon survives that circular crop.
try saveText(vector(size: 288, viewport: 288, stroke: pale, flare: orange, scale: 160 / 96, offset: 64),
             res + "drawable/ic_splash_logo.xml")

// Local visual QA, deliberately outside the bundled assets.
try png(raster(size: 384, logicalSize: 96, draw: launcher), "build/brand/launcher-preview.png")
for size in [22, 32] {
    for (mode, background, stroke, flare) in [("light", "#FFFFFF", ink, rust), ("dark", ink, pale, orange)] {
        try png(raster(size: size, logicalSize: 96) {
            $0.setFillColor(color(background))
            $0.fill(CGRect(x: 0, y: 0, width: 96, height: 96))
            mark($0, stroke: stroke, flare: flare)
        }, "build/brand/widget-\(mode)-\(size).png")
    }
}
try png(raster(size: 192, logicalSize: 108) {
    $0.addEllipse(in: CGRect(x: 0, y: 0, width: 108, height: 108))
    $0.clip()
    $0.setFillColor(color(ink))
    $0.fill(CGRect(x: 0, y: 0, width: 108, height: 108))
    $0.translateBy(x: adaptiveOffset, y: adaptiveOffset)
    $0.scaleBy(x: adaptiveScale, y: adaptiveScale)
    mark($0, stroke: pale, flare: orange)
}, "build/brand/adaptive-round-preview.png")
print("Generated logo C: Flutter assets, SVG sources, Android launcher/widget/splash resources, and build/brand previews.")
